#!/bin/bash
SitePort=$1

OutDate=$(echo | openssl s_client -connect ${SitePort} 2>/dev/null | openssl x509 -noout -enddate | awk -F'=' '{print $2}')

OutputDate=$(date -d "${OutDate}" "+%s")
SystemDate=$(date '+%s')

DiffTime=$(expr "${OutputDate}" - "${SystemDate}")

if [ "${DiffTime}" -ge 864000 ]
then
     echo "Certificate will expire on ${OutDate}"
     exit 0
else
     echo "Certificate is getting expire in less then 10 days on ${OutDate}. Please Renew."
     exit 2
fi
